package com.watsidev.barcaoneclone.model

import androidx.compose.material3.MaterialTheme
import com.watsidev.barcaoneclone.R

data class Matches2024Model(
    override val imageRes: Int,
    override val imageText: Int?,
    override val descriptionRes: Int? = null,
): PrimaryCardInterface

object MatchData{
    val matchList = listOf(
        Matches2024Model(
            R.drawable.barcelona5_2realmadrid,
            R.string.RealMadrid5_2Barcelona
        ),
        Matches2024Model(
            R.drawable.athetic0_2barcelona,
            R.string.Athletic_Barca
        ),
        Matches2024Model(
            R.drawable.barbastro0_4barcelona,
            R.string.Barbastro_Barca
        ),
        Matches2024Model(
            R.drawable.barcelona1_2atletico,
            R.string.Barca_Atletico
        ),
        Matches2024Model(
            R.drawable.barcelona0_1leganes,
            R.string.Barca_Leganes
        ),
        Matches2024Model(
            R.drawable.borussia2_3barcelona,
            R.string.Borussia_Barça
        ),
        Matches2024Model(
            R.drawable.realbetis2_2barcelona,
            R.string.Betis_Barca
        ),
        Matches2024Model(
            R.drawable.mallorca1_5barcelona,
            R.string.Mallorca_Barca
        ),
        Matches2024Model(
            R.drawable.barcelona1_2laspalma,
            R.string.Barca_LasPalmas
        ),
        Matches2024Model(
            R.drawable.barcelona3_0stade,
            R.string.Barca_Stade
        ),
        Matches2024Model(
            R.drawable.celtadevigo2_2barcelona,
            R.string.Celta_Barca
        ),
        Matches2024Model(
            R.drawable.realsociedad1_0barcelona,
            R.string.RealSociedad_Barca
        ),
        Matches2024Model(
            R.drawable.estrellaroja2_5barcelona,
            R.string.Estrella_Barca
        ),
        Matches2024Model(
            R.drawable.barcelona3_1espanyol,
            R.string.Barca_Espanyol
        ),
        Matches2024Model(
            R.drawable.realmadrid0_4barcelona,
            R.string.RealMadrid5_2Barcelona
        ),
        Matches2024Model(
            R.drawable.barcelona4_1bayern,
            R.string.Barca_Bayern
        ),
        Matches2024Model(
            R.drawable.barcelona5_1sevilla,
            R.string.Barca_Sevilla
        ),
        Matches2024Model(
            R.drawable.alaves0_3barcelona,
            R.string.Alaves_Barca
        ),
        Matches2024Model(
            R.drawable.barcelona5_0youngboys,
            R.string.Barca_YoungBoys
        ),
        Matches2024Model(
            R.drawable.osasuna4_2barcelona,
            R.string.Osasuna_Barca
        ),
        Matches2024Model(
            R.drawable.barcelona1_0getafe,
            R.string.Barca_Getafe
        ),
        Matches2024Model(
            R.drawable.villareal1_5barcelona,
            R.string.Villareal_Barca
        ),
        Matches2024Model(
            R.drawable.monaco2_1barcelona,
            R.string.Monaco_Barca
        ),
        Matches2024Model(
            R.drawable.girona1_4barcelona,
            R.string.Girona_Barca
        ),
        Matches2024Model(
            R.drawable.barcelona7_0valladolid,
            R.string.Barca_Valladolid
        ),
        Matches2024Model(
            R.drawable.rayovallecano1_2barcelona,
            R.string.Rayo_Barca
        ),
        Matches2024Model(
            R.drawable.barcelona2_1athletic,
            R.string.Barca_Athletic
        ),
        Matches2024Model(
            R.drawable.valencia1_2barcelona,
            R.string.Valencia_Barca
        ),
        Matches2024Model(
            R.drawable.barcelona0_3monaco,
            R.string.Barca_Monaco
        ),
        Matches2024Model(
            R.drawable.milan2_2barcelona,
            R.string.Barca_Milan
        ),
        Matches2024Model(
            R.drawable.realmadrid1_2barcelona,
            R.string.RealMadrid5_2Barcelona
        ),
        Matches2024Model(
            R.drawable.mancity2_2barcelona,
            R.string.Barca_ManCity
        ),
    )
}
